{"name": "test_add[a-b-输入数据a、b不合法]", "status": "broken", "statusDetails": {"message": "TypeError: '>' not supported between instances of 'str' and 'int'", "trace": "self = <test_case.test_case.TestCase object at 0x0000020F2E006F00>, a = 'a', b = 'b', expected = '输入数据a、b不合法'\n\n    @pytest.mark.parametrize('a,b,expected', GetData.get_add_data())\n    def test_add(self, a, b, expected):\n        caculator = Caculator(a, b)\n>       assert caculator.add() == expected\n\ntest_case.py:42: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <func.func.Caculator object at 0x0000020F2E043290>\n\n    def add(self):\n    \n>       if self.a > 99 or self.a < -99 or self.b > 99 or self.b < -99:\nE       TypeError: '>' not supported between instances of 'str' and 'int'\n\n..\\func\\func.py:32: TypeError"}, "parameters": [{"name": "a", "value": "'a'"}, {"name": "b", "value": "'b'"}, {"name": "expected", "value": "'输入数据a、b不合法'"}], "start": 1713455497440, "stop": 1713455497440, "uuid": "efbc49e6-fe20-4164-b025-28263fccc289", "historyId": "5cc9881211ce10f69ad22b9bfdafbcca", "testCaseId": "3263b5ece03e48eb17dd8325a22d0a48", "fullName": "test_case.test_case.TestCase#test_add", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_case"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "wangmin"}, {"name": "thread", "value": "12688-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_case"}]}