{"name": "用户输入运算数据a、b，运算规则不合法", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nZeroDivisionError: division by zero", "trace": "self = <test_case.test_case_04.TestCase object at 0x0000025865B179B0>, a = 10, b = 0, expected = 'ZeroDivisionError: division by zero'\n\n    @allure.title(\"用户输入运算数据a、b，运算规则不合法\")\n    @pytest.mark.test_zero_division_error\n    @pytest.mark.xfail\n    @pytest.mark.parametrize('a,b,expected', GetData.get_zero_division_error())\n    def test_zero_division_error(self, a, b, expected):\n        \"\"\"\n        测试div()函数对除数为0的异常进行异常提示\n        :param a: 模拟用户输入的数据 a\n        :param b: 模拟用户输入的数据 b\n        :param expected: 输出异常类型ZeroDivisionError，并输出异常提示：除数不能为0\n        :return: 返回异常类型ZeroDivisionError，并输出异常提示：除数不能为0\n        \"\"\"\n        caculator = Caculator(a, b)\n>       assert caculator.div() == expected\n\ntest_case_04.py:51: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <func.func.Caculator object at 0x0000025865B586B0>\n\n    def div(self):\n        if self.a > 99 or self.a < -99 or self.b > 99 or self.b < -99:\n            print(\"请输入范围为【-99, 99】的整数或浮点数\")\n            return \"参数大小超出范围\"\n    \n>       return self.a / self.b\nE       ZeroDivisionError: division by zero\n\n..\\func\\func.py:43: ZeroDivisionError"}, "description": "\n        测试div()函数对除数为0的异常进行异常提示\n        :param a: 模拟用户输入的数据 a\n        :param b: 模拟用户输入的数据 b\n        :param expected: 输出异常类型ZeroDivisionError，并输出异常提示：除数不能为0\n        :return: 返回异常类型ZeroDivisionError，并输出异常提示：除数不能为0\n        ", "parameters": [{"name": "a", "value": "10"}, {"name": "b", "value": "0"}, {"name": "expected", "value": "'ZeroDivisionError: division by zero'"}], "start": 1713874465241, "stop": 1713874465241, "uuid": "d5384178-4899-4639-9768-72696e7bebfe", "historyId": "6906bc2cee32084491702c2da9a995c1", "testCaseId": "ea084260e14b38557bbd87eb53986b69", "fullName": "test_case.test_case_04.TestCase#test_zero_division_error", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "tag", "value": "test_zero_division_error"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_case_04"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "wangmin"}, {"name": "thread", "value": "21192-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_case_04"}]}