{"name": "用户输入运算数据a、b, a、b的数据类型不合法", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: 输入数据a、b不合法\nassert False", "trace": "self = <test_case.test_case_02.TestCase object at 0x00000268E110D1C0>, a = 'a', b = 'b', expected = '输入数据a、b不合法'\n\n    @allure.title(\"用户输入运算数据a、b, a、b的数据类型不合法\")\n    @allure.testcase(\"http://192.168.40.134:8080/projects/CACULATOR/issues/CACULATOR-2?filter=allissues\",\n                     \"用例管理系统\")\n    @allure.issue(\"http://192.168.40.134:8080/projects/BUG/issues/BUG-1?filter=allopenissues\", \"Bug管理系统\")\n    @pytest.mark.xfail\n    @pytest.mark.test_data_type_error\n    @pytest.mark.parametrize('a,b,expected', GetData.get_data_type_error())\n    def test_add_data_type_error(self, a, b, expected):\n        \"\"\"\n        测试add()函数对输入数据的数据类型报错提示\n        :param a: 除int整型、float浮点型、double浮点型以外的其他数据类型\n        :param b: 除int整型、float浮点型、double浮点型以外的其他数据类型\n        :param expected: 输出报错提示: 输入的数据a、b数据类型不合法；\n        :return: 返回报错提示：输入的数据a、b数据类型不合法；\n        \"\"\"\n        # step3(a, b, expected)\n        with allure.step(\"1、输入数据a、b, a、b为除int整型、float浮点型、double浮点型以外的其他数据类型,调用add()方法；\"):\n            caculator = Caculator(a, b)\n            with open(\"../allure_print_screen/1.png\", mode=\"rb\") as f:\n                file = f.read()\n                allure.attach(file, \"报错页面截图\", attachment_type=allure.attachment_type.PNG)\n            try:\n                # 可能产生异常的代码块\n>               assert caculator.add() == expected\n\ntest_case_02.py:67: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <func.func.Caculator object at 0x00000268E1142960>\n\n    def add(self):\n    \n>       if self.a > 99 or self.a < -99 or self.b > 99 or self.b < -99:\nE       TypeError: '>' not supported between instances of 'str' and 'int'\n\n..\\func\\func.py:32: TypeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_case.test_case_02.TestCase object at 0x00000268E110D1C0>, a = 'a', b = 'b', expected = '输入数据a、b不合法'\n\n    @allure.title(\"用户输入运算数据a、b, a、b的数据类型不合法\")\n    @allure.testcase(\"http://192.168.40.134:8080/projects/CACULATOR/issues/CACULATOR-2?filter=allissues\",\n                     \"用例管理系统\")\n    @allure.issue(\"http://192.168.40.134:8080/projects/BUG/issues/BUG-1?filter=allopenissues\", \"Bug管理系统\")\n    @pytest.mark.xfail\n    @pytest.mark.test_data_type_error\n    @pytest.mark.parametrize('a,b,expected', GetData.get_data_type_error())\n    def test_add_data_type_error(self, a, b, expected):\n        \"\"\"\n        测试add()函数对输入数据的数据类型报错提示\n        :param a: 除int整型、float浮点型、double浮点型以外的其他数据类型\n        :param b: 除int整型、float浮点型、double浮点型以外的其他数据类型\n        :param expected: 输出报错提示: 输入的数据a、b数据类型不合法；\n        :return: 返回报错提示：输入的数据a、b数据类型不合法；\n        \"\"\"\n        # step3(a, b, expected)\n        with allure.step(\"1、输入数据a、b, a、b为除int整型、float浮点型、double浮点型以外的其他数据类型,调用add()方法；\"):\n            caculator = Caculator(a, b)\n            with open(\"../allure_print_screen/1.png\", mode=\"rb\") as f:\n                file = f.read()\n                allure.attach(file, \"报错页面截图\", attachment_type=allure.attachment_type.PNG)\n            try:\n                # 可能产生异常的代码块\n                assert caculator.add() == expected\n                logging.info(\"这是test_case_02测试用例\")\n    \n            except TypeError:\n                # 处理异常的代码块\n                logging.error(\"TypeError: 输入的数据a、b数据类型不合法\")\n>               assert False, \"输入数据a、b不合法\"\nE               AssertionError: 输入数据a、b不合法\nE               assert False\n\ntest_case_02.py:73: AssertionError"}, "description": "\n        测试add()函数对输入数据的数据类型报错提示\n        :param a: 除int整型、float浮点型、double浮点型以外的其他数据类型\n        :param b: 除int整型、float浮点型、double浮点型以外的其他数据类型\n        :param expected: 输出报错提示: 输入的数据a、b数据类型不合法；\n        :return: 返回报错提示：输入的数据a、b数据类型不合法；\n        ", "steps": [{"name": "1、输入数据a、b, a、b为除int整型、float浮点型、double浮点型以外的其他数据类型,调用add()方法；", "status": "failed", "statusDetails": {"message": "AssertionError: 输入数据a、b不合法\nassert False\n", "trace": "  File \"D:\\开发项目\\Caculator\\test_case\\test_case_02.py\", line 73, in test_add_data_type_error\n    assert False, \"输入数据a、b不合法\"\n"}, "attachments": [{"name": "报错页面截图", "source": "ac202d56-8c04-4b87-88fb-aa30fc3e0d9b-attachment.png", "type": "image/png"}], "start": 1714966874149, "stop": 1714966874163}], "attachments": [{"name": "log", "source": "18024c6e-2068-42d4-8885-4b4ceb0c1221-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "'a'"}, {"name": "b", "value": "'b'"}, {"name": "expected", "value": "'输入数据a、b不合法'"}], "start": 1714966874149, "stop": 1714966874163, "uuid": "1794d62d-4373-4b0a-86ff-788faae06b12", "historyId": "4095529d1a9b81bf6f294a3b34c7b045", "testCaseId": "fc3f193172e053d7630156f8f03e0a17", "fullName": "test_case.test_case_02.TestCase#test_add_data_type_error", "labels": [{"name": "tag", "value": "test_data_type_error"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_case_02"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "wangmin"}, {"name": "thread", "value": "14788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_case_02"}], "links": [{"type": "issue", "url": "http://192.168.40.134:8080/projects/BUG/issues/BUG-1?filter=allopenissues", "name": "Bug管理系统"}, {"type": "tms", "url": "http://192.168.40.134:8080/projects/CACULATOR/issues/CACULATOR-2?filter=allissues", "name": "用例管理系统"}]}