{"name": "用户输入运算数据a、b, 程序输出正确的结果", "status": "failed", "statusDetails": {"message": "AssertionError: 3\nassert (4.14159265 + 3) == 4.14159265\n +  where 4.14159265 = <bound method Caculator.add of <func.func.Caculator object at 0x000002A0A423A930>>()\n +    where <bound method Caculator.add of <func.func.Caculator object at 0x000002A0A423A930>> = <func.func.Caculator object at 0x000002A0A423A930>.add", "trace": "self = <test_case.test_case_01.TestCase object at 0x000002A0A411EA50>\na = 3.14159265, b = 1.0, expected = 4.14159265, i = 3\n\n    @allure.title(\"用户输入运算数据a、b, 程序输出正确的结果\")\n    @allure.testcase(\"http://192.168.40.134:8080/projects/CACULATOR/issues/CACULATOR-4?filter=allissues\",\n                     \"用例管理系统\")\n    @pytest.mark.test_normal\n    @pytest.mark.parametrize('a,b,expected,i', GetData.get_add_data())\n    def test_add(self, a, b, expected, i):\n        \"\"\"\n        测试add()函数\n        :param a: 用户输入的数据a\n        :param b: 用户输入的数据b\n        :param expected: 输出a加b的结果\n        :return: 返回a加b的结果\n        \"\"\"\n        # step1(a, b, expected)\n        with allure.step(\"1、输入数据a、b, 调用add()方法；\"):\n            caculator = Caculator(a, b)\n            with open(f\"../allure_print_screen/{i}.png\", mode=\"rb\") as f:\n                file = f.read()\n                allure.attach(file, \"报错页面截图\", attachment_type=allure.attachment_type.PNG)\n            try:\n                # 可能产生异常的代码块\n>               assert caculator.add() + i == expected, i\nE               AssertionError: 3\nE               assert (4.14159265 + 3) == 4.14159265\nE                +  where 4.14159265 = <bound method Caculator.add of <func.func.Caculator object at 0x000002A0A423A930>>()\nE                +    where <bound method Caculator.add of <func.func.Caculator object at 0x000002A0A423A930>> = <func.func.Caculator object at 0x000002A0A423A930>.add\n\ntest_case_01.py:66: AssertionError"}, "description": "\n        测试add()函数\n        :param a: 用户输入的数据a\n        :param b: 用户输入的数据b\n        :param expected: 输出a加b的结果\n        :return: 返回a加b的结果\n        ", "steps": [{"name": "1、输入数据a、b, 调用add()方法；", "status": "failed", "statusDetails": {"message": "AssertionError: 3\nassert (4.14159265 + 3) == 4.14159265\n +  where 4.14159265 = <bound method Caculator.add of <func.func.Caculator object at 0x000002A0A423A930>>()\n +    where <bound method Caculator.add of <func.func.Caculator object at 0x000002A0A423A930>> = <func.func.Caculator object at 0x000002A0A423A930>.add\n", "trace": "  File \"D:\\开发项目\\Caculator\\test_case\\test_case_01.py\", line 66, in test_add\n    assert caculator.add() + i == expected, i\n"}, "attachments": [{"name": "报错页面截图", "source": "51073736-dce9-41ba-afb7-60277345da50-attachment.png", "type": "image/png"}], "start": 1714384390300, "stop": 1714384390301}], "parameters": [{"name": "a", "value": "3.14159265"}, {"name": "b", "value": "1.0"}, {"name": "expected", "value": "4.14159265"}, {"name": "i", "value": "3"}], "start": 1714384390300, "stop": 1714384390301, "uuid": "014a5e56-d199-4f5f-8f11-c1b9eaaa356e", "historyId": "860ce7794eef753a4a77475f0a4f336c", "testCaseId": "b716330b98d44fcafb992142fcf6b5d2", "fullName": "test_case.test_case_01.TestCase#test_add", "labels": [{"name": "tag", "value": "test_normal"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_case_01"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "wangmin"}, {"name": "thread", "value": "9516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_case_01"}], "links": [{"type": "tms", "url": "http://192.168.40.134:8080/projects/CACULATOR/issues/CACULATOR-4?filter=allissues", "name": "用例管理系统"}]}